In [35]:
import os
import sys
import numpy as np
from random import randint

In [36]:
p=np.zeros(shape=(4,4)) 

In [37]:
x=np.array([1,2,1,1,3,4,4,1,2,4,1,4,3,4,4,4,3,1,3,2,3,3,3,4,2,2,3])
x

array([1, 2, 1, 1, 3, 4, 4, 1, 2, 4, 1, 4, 3, 4, 4, 4, 3, 1, 3, 2, 3, 3, 3,
       4, 2, 2, 3])

In [38]:
for t in range(len(x)):
    p[x[t-1]-1, x[t]-1] = p[x[t-1]-1, x[t]-1] + 1
p

array([[ 1.,  2.,  2.,  1.],
       [ 1.,  1.,  2.,  1.],
       [ 2.,  1.,  2.,  3.],
       [ 2.,  1.,  2.,  3.]])

In [39]:
for i in range(4):
    p[i,:] = p[i,:] / np.sum(p[i,:])
p

array([[ 0.16666667,  0.33333333,  0.33333333,  0.16666667],
       [ 0.2       ,  0.2       ,  0.4       ,  0.2       ],
       [ 0.25      ,  0.125     ,  0.25      ,  0.375     ],
       [ 0.25      ,  0.125     ,  0.25      ,  0.375     ]])