In [25]:
import os
import sys
import numpy as np
from random import randint

In [26]:
p=np.zeros(shape=(4,4)) 

In [27]:
x=np.array([[0,1,0,0],[0,0,0,1],[0,0,0,1],[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,1,0,0],[1,0,0,0],[0,0,1,0]])
x

array([[0, 1, 0, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 1],
       [1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 1, 0, 0],
       [1, 0, 0, 0],
       [0, 0, 1, 0]])

In [28]:
for t in range(len(x)):
    p=p+np.outer(x[t-1],x[t])
p

array([[ 0.,  1.,  1.,  0.],
       [ 1.,  0.,  1.,  1.],
       [ 0.,  2.,  0.,  0.],
       [ 1.,  0.,  0.,  1.]])

In [29]:
for i in range(4):
    if np.sum(p[i,:])==0:
        p[i,:]=np.zeros(4)
    else:
        p[i,:] = p[i,:] / np.sum(p[i,:])
p

array([[ 0.        ,  0.5       ,  0.5       ,  0.        ],
       [ 0.33333333,  0.        ,  0.33333333,  0.33333333],
       [ 0.        ,  1.        ,  0.        ,  0.        ],
       [ 0.5       ,  0.        ,  0.        ,  0.5       ]])